apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app2.fullname" . }} 
  labels:
    app: {{ include "app2.name" . }}
    Platform: spark
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app2.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app2.name" . }}
    spec:
      serviceAccountName: spark
      containers:
      - name: {{ include "app2.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: "/app2"
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/app2"
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: project_env
          value: {{ .Values.env.project_env }}
        - name: project_name
          value: {{ .Values.env.project_name }}
        - name: env_name
          value: {{ .Values.env.env_name }}
